{
'name': 'School Management',
'version': '16.0',
'author': 'Rahul Ranjan',
'depends': ['base', 'mail', 'sale_management'],
'category': 'Education System',
'description': 'storing students information',
'website': 'https://www.smschool.com',
'data': [
        'security/ir.model.access.csv',
        'wizard/create_school_info_view.xml',
        'views/school.xml',
        'views/payment_view.xml',
        'views/salesmodel.xml',
        # 'views/invoicingmodel.xml',
        'views/demo.xml',
        ],
        'installable': True,
        'application': True,
        'auto_install': False,   
}
